name: Build dev and push to GitHub-Pages

on:
  push:
    branches:
      - dev

jobs:
  build-and-deploy-to-gh-pages:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Install and Build 🔧
        run: |
          yarn
          env CI=false PUBLIC_URL=/smart-calculator-v2/dev yarn run build
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@releases/v4
        with:
          BRANCH: gh-pages
          FOLDER: build
          TARGET-FOLDER: dev
